### ISSUE TITLE
例子

### ISSUE THREAD

**Issue by NotHaozi** [T-head-Semi/csi-nn2#9]
1. 大哥能给个怎么用的例子吗？test里面是有例子，但是makefile文件没有公开，哈哈。（虽然可以自己写）
2. 比如能不能用CSI-NN2完成一个Lenet5的例子 。

非常感谢，这个库对我们很有帮助，我们打算移植到其他硬件平台上，谢谢！

**Comment by UCASHurui** [comment]
期待新的用例！如果能和具体的开发板（比如全志的D1）结合起来就好了

**Comment by zhangwm-pt** [comment]
> 期待新的用例！如果能和具体的开发板（比如全志的D1）结合起来就好了

与全志 D1 结合的示例直接参考 [HHB 的文档](https://www.yuque.com/za4k4z/oxlbxl/pruwva#hRtYI) 说明即可，里面有如何用工具将mobilenet 分解成 CSI-NN2 函数，然后执行在 d1 上的说明

**Comment by zhangwm-pt** [comment]
> 大哥 什麽時候更新呀

预计 10 月底

**Comment by zhangwm-pt** [comment]
已更新示例
